library(dplyr)
library(ggplot2)

################################################################################
# Semantic Analysis
#
# Using SpacyR package, pre-process Lemma and Root Words, Noun-Phrases
# and Entities and visualize in the Shiny app.
#
################################################################################

fnPlotTopRoots <- function(dfInRoots, topN){
  print(dfInRoots)
  
  dfInRoots %>% 
    group_by(word) %>%
    summarize(total=sum(n)) %>%
    arrange(desc(total)) %>%
    head(topN) %>%
    mutate(word = reorder(word, total)) %>%
    ggplot(aes(word, total)) +
    geom_bar(stat="identity") +
    xlab(NULL) + coord_flip()
}

fnGetTopEntities <- function(dfInEntities, topN){
  dfInEntities %>% 
    group_by(entity) %>%
    summarize(total=sum(n)) %>%
    arrange(desc(total)) %>%
    head(topN)
}

fnPlotTopEntities <- function(dfInEntities, topN){
  fnGetTopEntities(dfInEntities, topN) %>%
    mutate(entity = reorder(entity, total)) %>%
    ggplot(aes(entity, total)) +
    geom_bar(stat="identity") +
    xlab(NULL) + coord_flip()
}

fnPlotTopPhrases <- function(dfInPhrases, topN){
  # Extract meaningful "three-word" phrases from the semantic noun-phrases
  # generated by SpacyR
  dfInPhrases %>% 
    separate(phrase, c("first", "second", "third")) %>% 
    filter(!is.na(first) & !is.na(second) & !is.na(third)) %>%
    unite("phrase", first:third) %>% 
    group_by(phrase) %>% 
    summarize(total=sum(n)) %>% 
    arrange(desc(total)) %>%
    head(topN) %>% 
    mutate(phrase = reorder(phrase, total)) %>%
    ggplot(aes(phrase, total)) +
    geom_bar(stat="identity") +
    xlab(NULL) + coord_flip()
}

fnGetEntityTypeDescription <- function(){
  cEntityTypeDesc <- c(
    "PERSON", "People, including fictional.",
    "NORP", "Nationalities or religious or political groups.",
    "FAC", "Buildings, airports, highways, bridges, etc.",
    "ORG", "Companies, agencies, institutions, etc.",
    "GPE", "Countries, cities, states.",
    "LOC", "Non-GPE locations, mountain ranges, bodies of water.",
    "PRODUCT", "Objects, vehicles, foods, etc. (Not services.)",
    "EVENT", "Named hurricanes, battles, wars, sports events, etc.",
    "WORK_OF_ART", "Titles of books, songs, etc.",
    "LAW", "Named documents made into laws.",
    "LANGUAGE", "Any named language.",
    "DATE", "Absolute or relative dates or periods.",
    "TIME", "Times smaller than a day.",
    "PERCENT", "Percentage, including ”%“.",
    "MONEY", "Monetary values, including unit.",
    "QUANTITY", "Measurements, as of weight or distance.",
    "ORDINAL", "“first”, “second”, etc.",
    "CARDINAL", "Numerals that do not fall under another type."
  )
  
  as_tibble(t(matrix(cEntityTypeDesc, nrow=2)),)  %>% 
    rename(Type=V1,Description=V2)
}

fnPlotEntitiesByType <- function(dfInEntities, topN){
  # Only capturing key entity types (people, places, events, etc.)
  dfInEntities %>% 
    filter(entity_type %in% 
             c("EVENT", "PERSON", "NORP", "GPE", "LOC", "FAC")) %>%
    group_by(entity_type, entity) %>%
    summarise(n=n()) %>% 
    group_by(entity_type) %>%
    slice_max(order_by=n, n=topN) %>%
    ggplot(aes(x=entity, y=n)) +
    geom_bar(stat="identity") +
    coord_flip() +
    facet_wrap(~entity_type, scales="free")   
}